const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    // KEEP IT SIMPLE - this works on Render
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });
  }

  async sendSummary(email, summary, fileName) {
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: email,
      subject: `Sales Insight Summary - ${fileName}`,
      html: this.generateEmailTemplate(summary, fileName)
    };

    try {
      console.log('📧 Sending email to:', email);
      
      const info = await this.transporter.sendMail(mailOptions);
      console.log('✅ Email sent:', info.messageId);
      return { success: true };
    } catch (error) {
      console.error('❌ Email error:', error.message);
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }

  generateEmailTemplate(summary, fileName) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; }
          .content { padding: 20px; background: #f9f9f9; border-radius: 10px; margin-top: 20px; }
          .summary { white-space: pre-line; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Sales Insight Summary</h1>
            <p>File: ${fileName}</p>
          </div>
          <div class="content">
            <div class="summary">${summary.replace(/\n/g, '<br>')}</div>
          </div>
          <div class="footer">
            <p>Generated by Rabbit AI</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

module.exports = new EmailService();