const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      host: 'smtp.gmail.com',
      port: 587,
      secure: false, // true for 465, false for 587
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      },
      connectionTimeout: 60000, // 60 seconds
      greetingTimeout: 30000,    // 30 seconds
      socketTimeout: 60000,      // 60 seconds
      tls: {
        rejectUnauthorized: false // Only for development, remove in production
      },
      debug: true // Enable debug logs
    });
  }

  async sendSummary(email, summary, fileName) {
    const mailOptions = {
      from: `"Rabbit AI" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `📊 Sales Insight Summary - ${fileName}`,
      html: this.generateEmailTemplate(summary, fileName)
    };

    try {
      console.log('📧 Attempting to send email...');
      console.log('📧 SMTP Config:', {
        host: 'smtp.gmail.com',
        port: 587,
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS ? '✓ Set' : '✗ Missing'
      });

      const info = await this.transporter.sendMail(mailOptions);
      console.log('✅ Email sent successfully:', info.messageId);
      return { success: true, messageId: info.messageId };
    } catch (error) {
      console.error('❌ Email error details:', {
        message: error.message,
        code: error.code,
        command: error.command,
        response: error.response
      });
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }

  generateEmailTemplate(summary, fileName) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; }
          .content { padding: 20px; background: #f9f9f9; border-radius: 10px; margin-top: 20px; }
          .summary { white-space: pre-line; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📊 Sales Insight Summary</h1>
            <p>File: ${fileName}</p>
          </div>
          <div class="content">
            <div class="summary">${summary.replace(/\n/g, '<br>')}</div>
          </div>
          <div class="footer">
            <p>Generated by Rabbit AI Sales Insight Automator</p>
            <p>© ${new Date().getFullYear()} Rabbit AI. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

module.exports = new EmailService();