const { Resend } = require('resend');

class EmailService {
  constructor() {
    // Initialize Resend with API key
    this.resend = new Resend(process.env.RESEND_API_KEY);
    console.log('✅ Resend initialized');
  }

  async sendSummary(email, summary, fileName) {
    try {
      console.log('📧 Sending via Resend API to:', email);
      
      const { data, error } = await this.resend.emails.send({
        from: 'onboarding@resend.dev', // Resend's test domain - works immediately!
        to: [email],
        subject: `Sales Insight Summary - ${fileName}`,
        html: this.generateEmailTemplate(summary, fileName)
      });

      if (error) {
        console.error('❌ Resend error:', error);
        throw error;
      }

      console.log('✅ Email sent successfully via Resend!');
      return { success: true, data };
    } catch (error) {
      console.error('❌ Email error:', error);
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }

  generateEmailTemplate(summary, fileName) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; }
          .content { padding: 20px; background: #f9f9f9; border-radius: 10px; margin-top: 20px; }
          .summary { white-space: pre-line; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Sales Insight Summary</h1>
            <p>File: ${fileName}</p>
          </div>
          <div class="content">
            <div class="summary">${summary.replace(/\n/g, '<br>')}</div>
          </div>
          <div class="footer">
            <p>Generated by Rabbit AI</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

module.exports = new EmailService();